# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grist_client.models.patch_group_by_id_request_operations_inner import PatchGroupByIdRequestOperationsInner

class TestPatchGroupByIdRequestOperationsInner(unittest.TestCase):
    """PatchGroupByIdRequestOperationsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PatchGroupByIdRequestOperationsInner:
        """Test PatchGroupByIdRequestOperationsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PatchGroupByIdRequestOperationsInner`
        """
        model = PatchGroupByIdRequestOperationsInner()
        if include_optional:
            return PatchGroupByIdRequestOperationsInner(
                op = 'replace',
                path = members[display eq "John Doe"].value,
                value = 42
            )
        else:
            return PatchGroupByIdRequestOperationsInner(
        )
        """

    def testPatchGroupByIdRequestOperationsInner(self):
        """Test PatchGroupByIdRequestOperationsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
