# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grist_client.api.tables_api import TablesApi


class TestTablesApi(unittest.TestCase):
    """TablesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TablesApi()

    def tearDown(self) -> None:
        pass

    def test_add_tables(self) -> None:
        """Test case for add_tables

        Add tables to a document
        """
        pass

    def test_list_tables(self) -> None:
        """Test case for list_tables

        List tables in a document
        """
        pass

    def test_modify_tables(self) -> None:
        """Test case for modify_tables

        Modify tables of a document
        """
        pass


if __name__ == '__main__':
    unittest.main()
