# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grist_client.models.get_all_sessions200_response import GetAllSessions200Response

class TestGetAllSessions200Response(unittest.TestCase):
    """GetAllSessions200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAllSessions200Response:
        """Test GetAllSessions200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAllSessions200Response`
        """
        model = GetAllSessions200Response()
        if include_optional:
            return GetAllSessions200Response(
                users = [
                    grist_client.models.user.User(
                        id = 101, 
                        name = 'Helga Hufflepuff', 
                        picture = '', )
                    ],
                orgs = [
                    grist_client.models.org.Org(
                        id = 42, 
                        name = 'Grist Labs', 
                        domain = 'gristlabs', 
                        owner = grist_client.models.user.User(
                            id = 101, 
                            name = 'Helga Hufflepuff', 
                            picture = '', ), 
                        access = 'owners', 
                        created_at = '2019-09-13T15:42:35.000Z', 
                        updated_at = '2019-09-13T15:42:35.000Z', )
                    ]
            )
        else:
            return GetAllSessions200Response(
        )
        """

    def testGetAllSessions200Response(self):
        """Test GetAllSessions200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
