# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grist_client.api.session_api import SessionApi


class TestSessionApi(unittest.TestCase):
    """SessionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SessionApi()

    def tearDown(self) -> None:
        pass

    def test_get_active_session(self) -> None:
        """Test case for get_active_session

        Get active session information
        """
        pass

    def test_get_all_sessions(self) -> None:
        """Test case for get_all_sessions

        Get all session users and organizations
        """
        pass

    def test_set_active_user(self) -> None:
        """Test case for set_active_user

        Set active user for organization
        """
        pass


if __name__ == '__main__':
    unittest.main()
