# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grist_client.models.create_proposal200_response import CreateProposal200Response

class TestCreateProposal200Response(unittest.TestCase):
    """CreateProposal200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateProposal200Response:
        """Test CreateProposal200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateProposal200Response`
        """
        model = CreateProposal200Response()
        if include_optional:
            return CreateProposal200Response(
                id = 56,
                comparison = grist_client.models.doc_comparison.DocComparison(
                    left = grist_client.models.doc_comparison_left.DocComparison_left(
                        n = 56, 
                        h = '', ), 
                    right = grist_client.models.doc_comparison_right.DocComparison_right(
                        n = 56, 
                        h = '', ), 
                    parent = grist_client.models.doc_comparison_parent.DocComparison_parent(
                        n = 56, 
                        h = '', ), 
                    summary = 'same', 
                    details = grist_client.models.doc_comparison_details.DocComparison_details(
                        left_changes = grist_client.models.left_changes.leftChanges(), 
                        right_changes = grist_client.models.right_changes.rightChanges(), ), )
            )
        else:
            return CreateProposal200Response(
        )
        """

    def testCreateProposal200Response(self):
        """Test CreateProposal200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
