# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grist_client.models.create_fields import CreateFields

class TestCreateFields(unittest.TestCase):
    """CreateFields unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateFields:
        """Test CreateFields
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateFields`
        """
        model = CreateFields()
        if include_optional:
            return CreateFields(
                type = 'Any',
                label = '',
                formula = '',
                is_formula = True,
                widget_options = '',
                untie_col_id_from_label = True,
                recalc_when = 56,
                visible_col = 56,
                recalc_deps = ''
            )
        else:
            return CreateFields(
        )
        """

    def testCreateFields(self):
        """Test CreateFields"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
