# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grist_client.models.get_states200_response import GetStates200Response

class TestGetStates200Response(unittest.TestCase):
    """GetStates200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetStates200Response:
        """Test GetStates200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetStates200Response`
        """
        model = GetStates200Response()
        if include_optional:
            return GetStates200Response(
                states = [
                    grist_client.models.get_states_200_response_states_inner.getStates_200_response_states_inner(
                        n = 56, 
                        h = '', )
                    ]
            )
        else:
            return GetStates200Response(
                states = [
                    grist_client.models.get_states_200_response_states_inner.getStates_200_response_states_inner(
                        n = 56, 
                        h = '', )
                    ],
        )
        """

    def testGetStates200Response(self):
        """Test GetStates200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
