# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grist_client.models.get_form_data200_response import GetFormData200Response

class TestGetFormData200Response(unittest.TestCase):
    """GetFormData200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetFormData200Response:
        """Test GetFormData200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetFormData200Response`
        """
        model = GetFormData200Response()
        if include_optional:
            return GetFormData200Response(
                form_fields_by_id = None,
                form_layout_spec = '',
                form_table_id = '',
                form_title = ''
            )
        else:
            return GetFormData200Response(
        )
        """

    def testGetFormData200Response(self):
        """Test GetFormData200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
