# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grist_client.api.webhooks_api import WebhooksApi


class TestWebhooksApi(unittest.TestCase):
    """WebhooksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WebhooksApi()

    def tearDown(self) -> None:
        pass

    def test_clear_webhook_queue(self) -> None:
        """Test case for clear_webhook_queue

        Empty a document's queue of undelivered payloads
        """
        pass

    def test_clear_webhook_queue_for_webhook(self) -> None:
        """Test case for clear_webhook_queue_for_webhook

        Clear queue for a specific webhook
        """
        pass

    def test_create_webhooks(self) -> None:
        """Test case for create_webhooks

        Create new webhooks for a document
        """
        pass

    def test_delete_webhook(self) -> None:
        """Test case for delete_webhook

        Remove a webhook
        """
        pass

    def test_list_webhooks(self) -> None:
        """Test case for list_webhooks

        Webhooks associated with a document
        """
        pass

    def test_modify_webhook(self) -> None:
        """Test case for modify_webhook

        Modify a webhook
        """
        pass


if __name__ == '__main__':
    unittest.main()
