# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grist_client.api.scim_api import ScimApi


class TestScimApi(unittest.TestCase):
    """ScimApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ScimApi()

    def tearDown(self) -> None:
        pass

    def test_bulk_operation(self) -> None:
        """Test case for bulk_operation

        Bulk operation
        """
        pass

    def test_create_group(self) -> None:
        """Test case for create_group

        Create a new group
        """
        pass

    def test_create_user(self) -> None:
        """Test case for create_user

        Create a new user
        """
        pass

    def test_delete_group_by_id(self) -> None:
        """Test case for delete_group_by_id

        Delete a group by ID.
        """
        pass

    def test_delete_user_by_id(self) -> None:
        """Test case for delete_user_by_id

        Delete a user by ID.
        """
        pass

    def test_get_group_by_id(self) -> None:
        """Test case for get_group_by_id

        Retrieve group by ID
        """
        pass

    def test_get_groups(self) -> None:
        """Test case for get_groups

        Retrieve list of groups
        """
        pass

    def test_get_me(self) -> None:
        """Test case for get_me

        Retrieve information about oneself
        """
        pass

    def test_get_resource_types(self) -> None:
        """Test case for get_resource_types

        Retrieve SCIM resource types
        """
        pass

    def test_get_role_by_id(self) -> None:
        """Test case for get_role_by_id

        Retrieve role by ID
        """
        pass

    def test_get_roles(self) -> None:
        """Test case for get_roles

        Retrieve list of roles.
        """
        pass

    def test_get_schemas(self) -> None:
        """Test case for get_schemas

        Retrieve SCIM schemas
        """
        pass

    def test_get_service_provider_config(self) -> None:
        """Test case for get_service_provider_config

        Retrieve service provider configuration
        """
        pass

    def test_get_user_by_id(self) -> None:
        """Test case for get_user_by_id

        Retrieve user by ID
        """
        pass

    def test_get_users(self) -> None:
        """Test case for get_users

        Retrieve list of users
        """
        pass

    def test_patch_group_by_id(self) -> None:
        """Test case for patch_group_by_id

        Partially update a group by ID
        """
        pass

    def test_patch_role_by_id(self) -> None:
        """Test case for patch_role_by_id

        Partially update a role by ID
        """
        pass

    def test_patch_user_by_id(self) -> None:
        """Test case for patch_user_by_id

        Partially update a user by ID
        """
        pass

    def test_search_groups(self) -> None:
        """Test case for search_groups

        Search groups
        """
        pass

    def test_search_users(self) -> None:
        """Test case for search_users

        Search users
        """
        pass

    def test_update_group_by_id(self) -> None:
        """Test case for update_group_by_id

        Update a group by ID
        """
        pass

    def test_update_role_by_id(self) -> None:
        """Test case for update_role_by_id

        Update a role by ID
        """
        pass

    def test_update_user_by_id(self) -> None:
        """Test case for update_user_by_id

        Update a user by ID
        """
        pass


if __name__ == '__main__':
    unittest.main()
