# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grist_client.models.table_schema import TableSchema

class TestTableSchema(unittest.TestCase):
    """TableSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TableSchema:
        """Test TableSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TableSchema`
        """
        model = TableSchema()
        if include_optional:
            return TableSchema(
                fields = [
                    grist_client.models.table_schema_field.Table Schema Field()
                    ],
                primary_key = None,
                foreign_keys = [
                    grist_client.models.table_schema_foreign_key.Table Schema Foreign Key()
                    ],
                missing_values = [
                    ''
                    ]
            )
        else:
            return TableSchema(
                fields = [
                    grist_client.models.table_schema_field.Table Schema Field()
                    ],
        )
        """

    def testTableSchema(self):
        """Test TableSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
