# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grist_client.api.profile_api import ProfileApi


class TestProfileApi(unittest.TestCase):
    """ProfileApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProfileApi()

    def tearDown(self) -> None:
        pass

    def test_create_api_key(self) -> None:
        """Test case for create_api_key

        Create or regenerate API key
        """
        pass

    def test_delete_api_key(self) -> None:
        """Test case for delete_api_key

        Delete user's API key
        """
        pass

    def test_get_api_key(self) -> None:
        """Test case for get_api_key

        Get user's API key
        """
        pass

    def test_get_profile(self) -> None:
        """Test case for get_profile

        Get current user's profile
        """
        pass

    def test_update_user_locale(self) -> None:
        """Test case for update_user_locale

        Update user's locale
        """
        pass

    def test_update_user_name(self) -> None:
        """Test case for update_user_name

        Update user's name
        """
        pass


if __name__ == '__main__':
    unittest.main()
