# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grist_client.models.search_groups_request import SearchGroupsRequest

class TestSearchGroupsRequest(unittest.TestCase):
    """SearchGroupsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchGroupsRequest:
        """Test SearchGroupsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchGroupsRequest`
        """
        model = SearchGroupsRequest()
        if include_optional:
            return SearchGroupsRequest(
                schemas = [
                    'urn:ietf:params:scim:api:messages:2.0:SearchRequest'
                    ],
                filter = displayName eq "Engineering",
                sort_by = displayName,
                sort_order = 'ascending',
                attributes = ["id","displayName"],
                excluded_attributes = ["members"],
                start_index = 1,
                count = 10
            )
        else:
            return SearchGroupsRequest(
        )
        """

    def testSearchGroupsRequest(self):
        """Test SearchGroupsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
