# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grist_client.models.create_webhooks_request_webhooks_inner import CreateWebhooksRequestWebhooksInner

class TestCreateWebhooksRequestWebhooksInner(unittest.TestCase):
    """CreateWebhooksRequestWebhooksInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateWebhooksRequestWebhooksInner:
        """Test CreateWebhooksRequestWebhooksInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateWebhooksRequestWebhooksInner`
        """
        model = CreateWebhooksRequestWebhooksInner()
        if include_optional:
            return CreateWebhooksRequestWebhooksInner(
                fields = grist_client.models.webhook_partial_fields.WebhookPartialFields(
                    name = 'new-project-email', 
                    memo = 'Send an email when a project is added', 
                    url = 'https://example.com/webhook/123', 
                    enabled = True, 
                    event_types = ["add","update"], 
                    is_ready_column = '', 
                    table_id = 'Projects', )
            )
        else:
            return CreateWebhooksRequestWebhooksInner(
                fields = grist_client.models.webhook_partial_fields.WebhookPartialFields(
                    name = 'new-project-email', 
                    memo = 'Send an email when a project is added', 
                    url = 'https://example.com/webhook/123', 
                    enabled = True, 
                    event_types = ["add","update"], 
                    is_ready_column = '', 
                    table_id = 'Projects', ),
        )
        """

    def testCreateWebhooksRequestWebhooksInner(self):
        """Test CreateWebhooksRequestWebhooksInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
