# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grist_client.api.workspaces_api import WorkspacesApi


class TestWorkspacesApi(unittest.TestCase):
    """WorkspacesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkspacesApi()

    def tearDown(self) -> None:
        pass

    def test_create_workspace(self) -> None:
        """Test case for create_workspace

        Create an empty workspace
        """
        pass

    def test_delete_workspace(self) -> None:
        """Test case for delete_workspace

        Delete a workspace
        """
        pass

    def test_describe_workspace(self) -> None:
        """Test case for describe_workspace

        Describe a workspace
        """
        pass

    def test_list_workspace_access(self) -> None:
        """Test case for list_workspace_access

        List users with access to workspace
        """
        pass

    def test_list_workspaces(self) -> None:
        """Test case for list_workspaces

        List workspaces and documents within an org
        """
        pass

    def test_modify_workspace(self) -> None:
        """Test case for modify_workspace

        Modify a workspace
        """
        pass

    def test_modify_workspace_access(self) -> None:
        """Test case for modify_workspace_access

        Change who has access to workspace
        """
        pass

    def test_remove_workspace(self) -> None:
        """Test case for remove_workspace

        Move workspace to trash
        """
        pass

    def test_unremove_workspace(self) -> None:
        """Test case for unremove_workspace

        Restore workspace from trash
        """
        pass


if __name__ == '__main__':
    unittest.main()
