# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grist_client.api.widgets_api import WidgetsApi


class TestWidgetsApi(unittest.TestCase):
    """WidgetsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WidgetsApi()

    def tearDown(self) -> None:
        pass

    def test_list_widgets(self) -> None:
        """Test case for list_widgets

        List available custom widgets
        """
        pass


if __name__ == '__main__':
    unittest.main()
