# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grist_client.models.list_snapshots200_response import ListSnapshots200Response

class TestListSnapshots200Response(unittest.TestCase):
    """ListSnapshots200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListSnapshots200Response:
        """Test ListSnapshots200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListSnapshots200Response`
        """
        model = ListSnapshots200Response()
        if include_optional:
            return ListSnapshots200Response(
                snapshots = [
                    grist_client.models.list_snapshots_200_response_snapshots_inner.listSnapshots_200_response_snapshots_inner(
                        snapshot_id = '', 
                        last_modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        doc_id = '', )
                    ]
            )
        else:
            return ListSnapshots200Response(
                snapshots = [
                    grist_client.models.list_snapshots_200_response_snapshots_inner.listSnapshots_200_response_snapshots_inner(
                        snapshot_id = '', 
                        last_modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        doc_id = '', )
                    ],
        )
        """

    def testListSnapshots200Response(self):
        """Test ListSnapshots200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
