# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grist_client.models.service_account_body import ServiceAccountBody

class TestServiceAccountBody(unittest.TestCase):
    """ServiceAccountBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceAccountBody:
        """Test ServiceAccountBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceAccountBody`
        """
        model = ServiceAccountBody()
        if include_optional:
            return ServiceAccountBody(
                label = 'n8n',
                description = 'For data update workflow',
                expires_at = '2042-10-10'
            )
        else:
            return ServiceAccountBody(
        )
        """

    def testServiceAccountBody(self):
        """Test ServiceAccountBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
