# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grist_client.api.data_api import DataApi


class TestDataApi(unittest.TestCase):
    """DataApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DataApi()

    def tearDown(self) -> None:
        pass

    def test_add_rows(self) -> None:
        """Test case for add_rows

        Add rows to a table
        """
        pass

    def test_delete_rows(self) -> None:
        """Test case for delete_rows

        Delete rows of a table
        """
        pass

    def test_get_table_data(self) -> None:
        """Test case for get_table_data

        Fetch data from a table
        """
        pass

    def test_modify_rows(self) -> None:
        """Test case for modify_rows

        Modify rows of a table
        """
        pass


if __name__ == '__main__':
    unittest.main()
