# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grist_client.models.list_webhooks200_response import ListWebhooks200Response

class TestListWebhooks200Response(unittest.TestCase):
    """ListWebhooks200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListWebhooks200Response:
        """Test ListWebhooks200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListWebhooks200Response`
        """
        model = ListWebhooks200Response()
        if include_optional:
            return ListWebhooks200Response(
                webhooks = [
                    grist_client.models.webhook.Webhook(
                        id = '', 
                        fields = null, 
                        usage = grist_client.models.webhook_usage.WebhookUsage(
                            num_waiting = 56, 
                            status = 'idle', 
                            updated_time = 1685637500424, 
                            last_success_time = 1685637500424, 
                            last_failure_time = 1685637500424, 
                            last_error_message = '', 
                            last_http_status = 200, 
                            last_event_batch = grist_client.models.webhook_batch_status.WebhookBatchStatus(
                                size = 1, 
                                attempts = 1, 
                                error_message = '', 
                                http_status = 200, 
                                status = 'success', ), ), )
                    ]
            )
        else:
            return ListWebhooks200Response(
                webhooks = [
                    grist_client.models.webhook.Webhook(
                        id = '', 
                        fields = null, 
                        usage = grist_client.models.webhook_usage.WebhookUsage(
                            num_waiting = 56, 
                            status = 'idle', 
                            updated_time = 1685637500424, 
                            last_success_time = 1685637500424, 
                            last_failure_time = 1685637500424, 
                            last_error_message = '', 
                            last_http_status = 200, 
                            last_event_batch = grist_client.models.webhook_batch_status.WebhookBatchStatus(
                                size = 1, 
                                attempts = 1, 
                                error_message = '', 
                                http_status = 200, 
                                status = 'success', ), ), )
                    ],
        )
        """

    def testListWebhooks200Response(self):
        """Test ListWebhooks200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
