# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grist_client.api.users_api import UsersApi


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UsersApi()

    def tearDown(self) -> None:
        pass

    def test_delete_user(self) -> None:
        """Test case for delete_user

        Delete a user from Grist
        """
        pass

    def test_disable_user(self) -> None:
        """Test case for disable_user

        Disable a user
        """
        pass

    def test_enable_user(self) -> None:
        """Test case for enable_user

        Enable a user
        """
        pass


if __name__ == '__main__':
    unittest.main()
