# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grist_client.api.columns_api import ColumnsApi


class TestColumnsApi(unittest.TestCase):
    """ColumnsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ColumnsApi()

    def tearDown(self) -> None:
        pass

    def test_add_columns(self) -> None:
        """Test case for add_columns

        Add columns to a table
        """
        pass

    def test_delete_column(self) -> None:
        """Test case for delete_column

        Delete a column of a table
        """
        pass

    def test_list_columns(self) -> None:
        """Test case for list_columns

        List columns in a table
        """
        pass

    def test_modify_columns(self) -> None:
        """Test case for modify_columns

        Modify columns of a table
        """
        pass

    def test_replace_columns(self) -> None:
        """Test case for replace_columns

        Add or update columns of a table
        """
        pass


if __name__ == '__main__':
    unittest.main()
