# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grist_client.models.workspace_access_read import WorkspaceAccessRead

class TestWorkspaceAccessRead(unittest.TestCase):
    """WorkspaceAccessRead unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkspaceAccessRead:
        """Test WorkspaceAccessRead
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkspaceAccessRead`
        """
        model = WorkspaceAccessRead()
        if include_optional:
            return WorkspaceAccessRead(
                max_inherited_role = 'owners',
                users = [
                    grist_client.models.workspace_access_read_users_inner.WorkspaceAccessRead_users_inner(
                        id = 1, 
                        name = 'Andrea', 
                        email = 'andrea@getgrist.com', 
                        access = 'owners', 
                        parent_access = 'owners', )
                    ]
            )
        else:
            return WorkspaceAccessRead(
                max_inherited_role = 'owners',
                users = [
                    grist_client.models.workspace_access_read_users_inner.WorkspaceAccessRead_users_inner(
                        id = 1, 
                        name = 'Andrea', 
                        email = 'andrea@getgrist.com', 
                        access = 'owners', 
                        parent_access = 'owners', )
                    ],
        )
        """

    def testWorkspaceAccessRead(self):
        """Test WorkspaceAccessRead"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
