# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grist_client.models.doc import Doc

class TestDoc(unittest.TestCase):
    """Doc unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Doc:
        """Test Doc
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Doc`
        """
        model = Doc()
        if include_optional:
            return Doc(
                id = '145',
                name = 'Project Lollipop',
                access = 'owners',
                is_pinned = True,
                url_id = ''
            )
        else:
            return Doc(
                id = '145',
                name = 'Project Lollipop',
                access = 'owners',
                is_pinned = True,
                url_id = '',
        )
        """

    def testDoc(self):
        """Test Doc"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
