# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grist_client.models.upload_missing_attachments200_response import UploadMissingAttachments200Response

class TestUploadMissingAttachments200Response(unittest.TestCase):
    """UploadMissingAttachments200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UploadMissingAttachments200Response:
        """Test UploadMissingAttachments200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UploadMissingAttachments200Response`
        """
        model = UploadMissingAttachments200Response()
        if include_optional:
            return UploadMissingAttachments200Response(
                added = 56,
                errored = 56,
                unused = 56
            )
        else:
            return UploadMissingAttachments200Response(
        )
        """

    def testUploadMissingAttachments200Response(self):
        """Test UploadMissingAttachments200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
