# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grist_client.api.docs_api import DocsApi


class TestDocsApi(unittest.TestCase):
    """DocsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DocsApi()

    def tearDown(self) -> None:
        pass

    def test_apply_proposal(self) -> None:
        """Test case for apply_proposal

        Apply a change proposal
        """
        pass

    def test_apply_user_actions(self) -> None:
        """Test case for apply_user_actions

        Apply a list of user actions
        """
        pass

    def test_assign_doc(self) -> None:
        """Test case for assign_doc

        Reassign document to appropriate worker
        """
        pass

    def test_compare_documents(self) -> None:
        """Test case for compare_documents

        Compare two documents
        """
        pass

    def test_compare_versions(self) -> None:
        """Test case for compare_versions

        Compare document versions
        """
        pass

    def test_copy_doc(self) -> None:
        """Test case for copy_doc

        Copies a document to a workspace.
        """
        pass

    def test_create_doc(self) -> None:
        """Test case for create_doc

        Create an empty document
        """
        pass

    def test_create_doc_unified(self) -> None:
        """Test case for create_doc_unified

        Create a document
        """
        pass

    def test_create_proposal(self) -> None:
        """Test case for create_proposal

        Create a change proposal
        """
        pass

    def test_delete_actions(self) -> None:
        """Test case for delete_actions

        Truncate the document's action history
        """
        pass

    def test_delete_doc(self) -> None:
        """Test case for delete_doc

        Delete a document
        """
        pass

    def test_describe_doc(self) -> None:
        """Test case for describe_doc

        Describe a document
        """
        pass

    def test_disable_doc(self) -> None:
        """Test case for disable_doc

        Disable a document.
        """
        pass

    def test_download_doc(self) -> None:
        """Test case for download_doc

        Content of document, as an Sqlite file
        """
        pass

    def test_download_doc_csv(self) -> None:
        """Test case for download_doc_csv

        Content of table, as a CSV file
        """
        pass

    def test_download_doc_dsv(self) -> None:
        """Test case for download_doc_dsv

        Content of table, as a DSV file
        """
        pass

    def test_download_doc_tsv(self) -> None:
        """Test case for download_doc_tsv

        Content of table, as a TSV file
        """
        pass

    def test_download_doc_xlsx(self) -> None:
        """Test case for download_doc_xlsx

        Content of document, as an Excel file
        """
        pass

    def test_download_table_schema(self) -> None:
        """Test case for download_table_schema

        The schema of a table
        """
        pass

    def test_enable_doc(self) -> None:
        """Test case for enable_doc

        Enable a document.
        """
        pass

    def test_flush_doc(self) -> None:
        """Test case for flush_doc

        Flush document to storage
        """
        pass

    def test_force_reload(self) -> None:
        """Test case for force_reload

        Reload a document
        """
        pass

    def test_fork_doc(self) -> None:
        """Test case for fork_doc

        Fork a document
        """
        pass

    def test_get_states(self) -> None:
        """Test case for get_states

        Get document action history states
        """
        pass

    def test_get_timing_status(self) -> None:
        """Test case for get_timing_status

        Get formula timing status
        """
        pass

    def test_get_users_for_view_as(self) -> None:
        """Test case for get_users_for_view_as

        Get users for 'View As' feature
        """
        pass

    def test_import_doc(self) -> None:
        """Test case for import_doc

        Import an existing document
        """
        pass

    def test_list_doc_access(self) -> None:
        """Test case for list_doc_access

        List users with access to document
        """
        pass

    def test_list_proposals(self) -> None:
        """Test case for list_proposals

        List change proposals
        """
        pass

    def test_list_snapshots(self) -> None:
        """Test case for list_snapshots

        List document snapshots
        """
        pass

    def test_modify_doc(self) -> None:
        """Test case for modify_doc

        Modify document metadata (but not its contents)
        """
        pass

    def test_modify_doc_access(self) -> None:
        """Test case for modify_doc_access

        Change who has access to document
        """
        pass

    def test_move_doc(self) -> None:
        """Test case for move_doc

        Move document to another workspace.
        """
        pass

    def test_pin_doc(self) -> None:
        """Test case for pin_doc

        Pin a document
        """
        pass

    def test_recover_doc(self) -> None:
        """Test case for recover_doc

        Set recovery mode for a document
        """
        pass

    def test_remove_doc(self) -> None:
        """Test case for remove_doc

        Move document to trash
        """
        pass

    def test_remove_snapshots(self) -> None:
        """Test case for remove_snapshots

        Remove document snapshots
        """
        pass

    def test_replace_doc(self) -> None:
        """Test case for replace_doc

        Replace document content
        """
        pass

    def test_start_timing(self) -> None:
        """Test case for start_timing

        Start formula timing
        """
        pass

    def test_stop_timing(self) -> None:
        """Test case for stop_timing

        Stop formula timing
        """
        pass

    def test_unpin_doc(self) -> None:
        """Test case for unpin_doc

        Unpin a document
        """
        pass

    def test_unremove_doc(self) -> None:
        """Test case for unremove_doc

        Restore document from trash
        """
        pass


if __name__ == '__main__':
    unittest.main()
