# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grist_client.models.webhook_usage import WebhookUsage

class TestWebhookUsage(unittest.TestCase):
    """WebhookUsage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebhookUsage:
        """Test WebhookUsage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebhookUsage`
        """
        model = WebhookUsage()
        if include_optional:
            return WebhookUsage(
                num_waiting = 56,
                status = 'idle',
                updated_time = 1685637500424,
                last_success_time = 1685637500424,
                last_failure_time = 1685637500424,
                last_error_message = '',
                last_http_status = 200,
                last_event_batch = grist_client.models.webhook_batch_status.WebhookBatchStatus(
                    size = 1, 
                    attempts = 1, 
                    error_message = '', 
                    http_status = 200, 
                    status = 'success', )
            )
        else:
            return WebhookUsage(
                num_waiting = 56,
                status = 'idle',
        )
        """

    def testWebhookUsage(self):
        """Test WebhookUsage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
