# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grist_client.models.get_org_usage200_response_counts_by_data_limit_status import GetOrgUsage200ResponseCountsByDataLimitStatus

class TestGetOrgUsage200ResponseCountsByDataLimitStatus(unittest.TestCase):
    """GetOrgUsage200ResponseCountsByDataLimitStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetOrgUsage200ResponseCountsByDataLimitStatus:
        """Test GetOrgUsage200ResponseCountsByDataLimitStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetOrgUsage200ResponseCountsByDataLimitStatus`
        """
        model = GetOrgUsage200ResponseCountsByDataLimitStatus()
        if include_optional:
            return GetOrgUsage200ResponseCountsByDataLimitStatus(
                approaching_limit = 56,
                grace_period = 56,
                delete_only = 56
            )
        else:
            return GetOrgUsage200ResponseCountsByDataLimitStatus(
        )
        """

    def testGetOrgUsage200ResponseCountsByDataLimitStatus(self):
        """Test GetOrgUsage200ResponseCountsByDataLimitStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
