# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grist_client.models.access import Access

class TestAccess(unittest.TestCase):
    """Access unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccess(self):
        """Test Access"""
        # inst = Access()

if __name__ == '__main__':
    unittest.main()
