# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grist_client.models.post_search import PostSearch

class TestPostSearch(unittest.TestCase):
    """PostSearch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostSearch:
        """Test PostSearch
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostSearch`
        """
        model = PostSearch()
        if include_optional:
            return PostSearch(
                schemas = [
                    'urn:ietf:params:scim:api:messages:2.0:SearchRequest'
                    ],
                filter = 'userName co "john.doe"',
                sort_by = 'userName',
                sort_order = 'ascending',
                attributes = [
                    ''
                    ],
                excluded_attributes = [
                    ''
                    ],
                start_index = 1,
                count = 10
            )
        else:
            return PostSearch(
        )
        """

    def testPostSearch(self):
        """Test PostSearch"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
