# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grist_client.models.csv_dialect import CsvDialect

class TestCsvDialect(unittest.TestCase):
    """CsvDialect unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CsvDialect:
        """Test CsvDialect
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CsvDialect`
        """
        model = CsvDialect()
        if include_optional:
            return CsvDialect(
                csvddf_version = 1.337,
                delimiter = ',',
                double_quote = True,
                line_terminator = '  ',
                null_sequence = '',
                quote_char = '"',
                escape_char = '',
                skip_initial_space = True,
                header = True,
                comment_char = '',
                case_sensitive_header = True
            )
        else:
            return CsvDialect(
                delimiter = ',',
                double_quote = True,
        )
        """

    def testCsvDialect(self):
        """Test CsvDialect"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
