# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grist_client.models.user_in_response import UserInResponse

class TestUserInResponse(unittest.TestCase):
    """UserInResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserInResponse:
        """Test UserInResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserInResponse`
        """
        model = UserInResponse()
        if include_optional:
            return UserInResponse(
                schemas = [
                    'urn:ietf:params:scim:schemas:core:2.0:User'
                    ],
                user_name = 'john.doe@example.com',
                name = grist_client.models.user_in_request_name.UserInRequest_name(
                    formatted = 'John Doe', ),
                emails = [
                    grist_client.models.user_in_request_emails_inner.UserInRequest_emails_inner(
                        value = 'john.doe@example.com', 
                        primary = True, )
                    ],
                display_name = 'John Doe',
                preferred_language = 'en',
                locale = 'en',
                photos = [
                    grist_client.models.user_in_request_photos_inner.UserInRequest_photos_inner(
                        value = 'https://example.com/pics/john-doe.png', 
                        primary = True, 
                        type = 'photo', )
                    ],
                meta = grist_client.models.user_in_response_all_of_meta.UserInResponse_allOf_meta(
                    resource_type = 'User', 
                    location = '/api/scim/v2/Users/1', ),
                id = '1'
            )
        else:
            return UserInResponse(
        )
        """

    def testUserInResponse(self):
        """Test UserInResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
