# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grist_client.models.tables_list import TablesList

class TestTablesList(unittest.TestCase):
    """TablesList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TablesList:
        """Test TablesList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TablesList`
        """
        model = TablesList()
        if include_optional:
            return TablesList(
                tables = [
                    grist_client.models.tables_list_tables_inner.TablesList_tables_inner(
                        id = 'Table1', 
                        fields = grist_client.models.tables_list_tables_inner_fields.TablesList_tables_inner_fields(
                            table_ref = 56, 
                            on_demand = True, ), 
                        columns = [
                            grist_client.models.tables_list_tables_inner_columns_inner.TablesList_tables_inner_columns_inner(
                                id = 'ColumnName', 
                                fields = null, )
                            ], )
                    ]
            )
        else:
            return TablesList(
                tables = [
                    grist_client.models.tables_list_tables_inner.TablesList_tables_inner(
                        id = 'Table1', 
                        fields = grist_client.models.tables_list_tables_inner_fields.TablesList_tables_inner_fields(
                            table_ref = 56, 
                            on_demand = True, ), 
                        columns = [
                            grist_client.models.tables_list_tables_inner_columns_inner.TablesList_tables_inner_columns_inner(
                                id = 'ColumnName', 
                                fields = null, )
                            ], )
                    ],
        )
        """

    def testTablesList(self):
        """Test TablesList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
