# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grist_client.models.workspace_with_org import WorkspaceWithOrg

class TestWorkspaceWithOrg(unittest.TestCase):
    """WorkspaceWithOrg unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkspaceWithOrg:
        """Test WorkspaceWithOrg
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkspaceWithOrg`
        """
        model = WorkspaceWithOrg()
        if include_optional:
            return WorkspaceWithOrg(
                id = 97,
                name = 'Secret Plans',
                access = 'owners',
                org = grist_client.models.org.Org(
                    id = 42, 
                    name = 'Grist Labs', 
                    domain = 'gristlabs', 
                    owner = grist_client.models.user.User(
                        id = 101, 
                        name = 'Helga Hufflepuff', 
                        picture = '', ), 
                    access = 'owners', 
                    created_at = '2019-09-13T15:42:35.000Z', 
                    updated_at = '2019-09-13T15:42:35.000Z', )
            )
        else:
            return WorkspaceWithOrg(
                id = 97,
                name = 'Secret Plans',
                access = 'owners',
                org = grist_client.models.org.Org(
                    id = 42, 
                    name = 'Grist Labs', 
                    domain = 'gristlabs', 
                    owner = grist_client.models.user.User(
                        id = 101, 
                        name = 'Helga Hufflepuff', 
                        picture = '', ), 
                    access = 'owners', 
                    created_at = '2019-09-13T15:42:35.000Z', 
                    updated_at = '2019-09-13T15:42:35.000Z', ),
        )
        """

    def testWorkspaceWithOrg(self):
        """Test WorkspaceWithOrg"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
