# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grist_client.api.orgs_api import OrgsApi


class TestOrgsApi(unittest.TestCase):
    """OrgsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrgsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_org(self) -> None:
        """Test case for delete_org

        Delete an org
        """
        pass

    def test_describe_org(self) -> None:
        """Test case for describe_org

        Describe an org
        """
        pass

    def test_get_org_usage(self) -> None:
        """Test case for get_org_usage

        Get organization usage summary
        """
        pass

    def test_list_org_access(self) -> None:
        """Test case for list_org_access

        List users with access to org
        """
        pass

    def test_list_orgs(self) -> None:
        """Test case for list_orgs

        List the orgs you have access to
        """
        pass

    def test_modify_org(self) -> None:
        """Test case for modify_org

        Modify an org
        """
        pass

    def test_modify_org_access(self) -> None:
        """Test case for modify_org_access

        Change who has access to org
        """
        pass


if __name__ == '__main__':
    unittest.main()
