# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grist_client.models.workspace_with_docs_and_domain import WorkspaceWithDocsAndDomain

class TestWorkspaceWithDocsAndDomain(unittest.TestCase):
    """WorkspaceWithDocsAndDomain unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkspaceWithDocsAndDomain:
        """Test WorkspaceWithDocsAndDomain
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkspaceWithDocsAndDomain`
        """
        model = WorkspaceWithDocsAndDomain()
        if include_optional:
            return WorkspaceWithDocsAndDomain(
                id = 97,
                name = 'Secret Plans',
                access = 'owners',
                docs = [
                    grist_client.models.doc.Doc(
                        id = '145', 
                        name = 'Project Lollipop', 
                        access = 'owners', 
                        is_pinned = True, 
                        url_id = '', )
                    ],
                org_domain = 'gristlabs'
            )
        else:
            return WorkspaceWithDocsAndDomain(
                id = 97,
                name = 'Secret Plans',
                access = 'owners',
                docs = [
                    grist_client.models.doc.Doc(
                        id = '145', 
                        name = 'Project Lollipop', 
                        access = 'owners', 
                        is_pinned = True, 
                        url_id = '', )
                    ],
        )
        """

    def testWorkspaceWithDocsAndDomain(self):
        """Test WorkspaceWithDocsAndDomain"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
