# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grist_client.models.fork_doc200_response import ForkDoc200Response

class TestForkDoc200Response(unittest.TestCase):
    """ForkDoc200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ForkDoc200Response:
        """Test ForkDoc200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ForkDoc200Response`
        """
        model = ForkDoc200Response()
        if include_optional:
            return ForkDoc200Response(
                fork_id = 'abc123',
                doc_id = 'XXXXX~abc123',
                url_id = 'UUUUU~abc123'
            )
        else:
            return ForkDoc200Response(
                fork_id = 'abc123',
                doc_id = 'XXXXX~abc123',
                url_id = 'UUUUU~abc123',
        )
        """

    def testForkDoc200Response(self):
        """Test ForkDoc200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
