# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from grist_client.models.patch_user_by_id_request import PatchUserByIdRequest

class TestPatchUserByIdRequest(unittest.TestCase):
    """PatchUserByIdRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PatchUserByIdRequest:
        """Test PatchUserByIdRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PatchUserByIdRequest`
        """
        model = PatchUserByIdRequest()
        if include_optional:
            return PatchUserByIdRequest(
                schemas = [
                    'urn:ietf:params:scim:api:messages:2.0:PatchOp'
                    ],
                operations = [
                    null
                    ]
            )
        else:
            return PatchUserByIdRequest(
        )
        """

    def testPatchUserByIdRequest(self):
        """Test PatchUserByIdRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
