# coding: utf-8

"""
    drive API

    This is the drive API schema.

    The version of the OpenAPI document: 1.0.0 (v1.0)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class LanguageEnum(str, Enum):
    """
    * `en-us` - English * `fr-fr` - French * `de-de` - German * `nl-nl` - Dutch
    """

    """
    allowed enum values
    """
    EN_MINUS_US = 'en-us'
    FR_MINUS_FR = 'fr-fr'
    DE_MINUS_DE = 'de-de'
    NL_MINUS_NL = 'nl-nl'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of LanguageEnum from a JSON string"""
        return cls(json.loads(json_str))


