# coding: utf-8

"""
    drive API

    This is the drive API schema.

    The version of the OpenAPI document: 1.0.0 (v1.0)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from openapi_client.models.link_role_enum import LinkRoleEnum
from openapi_client.models.restriction_target import RestrictionTarget
from openapi_client.models.type_enum import TypeEnum
from openapi_client.models.user_light import UserLight
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ListItem(BaseModel):
    """
    Serialize items with limited fields for display in lists.
    """ # noqa: E501
    id: UUID = Field(description="primary key for the record as UUID")
    abilities: Dict[str, Any] = Field(description="Return abilities of the logged-in user on the instance.")
    ancestors_link_reach: StrictStr
    ancestors_link_role: StrictStr
    computed_link_reach: StrictStr
    computed_link_role: StrictStr
    created_at: datetime = Field(description="date and time at which a record was created")
    creator: UserLight
    depth: StrictStr
    is_favorite: StrictBool
    link_role: LinkRoleEnum
    link_reach: Optional[StrictStr]
    is_restricted: StrictStr
    nb_accesses: StrictInt
    numchild: StrictStr
    numchild_folder: StrictStr
    path: StrictStr
    target: Optional[RestrictionTarget]
    title: Annotated[str, Field(strict=True, max_length=255)]
    updated_at: datetime = Field(description="date and time at which a record was last updated")
    user_role: StrictStr
    type: TypeEnum
    upload_state: Optional[StrictStr]
    url: StrictStr
    url_permalink: StrictStr
    url_preview: StrictStr
    filename: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    mimetype: Optional[StrictStr]
    main_workspace: StrictBool
    size: Optional[StrictInt]
    description: Optional[StrictStr]
    deleted_at: Optional[datetime]
    hard_delete_at: StrictStr
    is_wopi_supported: StrictStr
    __properties: ClassVar[List[str]] = ["id", "abilities", "ancestors_link_reach", "ancestors_link_role", "computed_link_reach", "computed_link_role", "created_at", "creator", "depth", "is_favorite", "link_role", "link_reach", "is_restricted", "nb_accesses", "numchild", "numchild_folder", "path", "target", "title", "updated_at", "user_role", "type", "upload_state", "url", "url_permalink", "url_preview", "filename", "mimetype", "main_workspace", "size", "description", "deleted_at", "hard_delete_at", "is_wopi_supported"]

    @field_validator('link_reach')
    def link_reach_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['restricted', 'authenticated', 'public']):
            raise ValueError("must be one of enum values ('restricted', 'authenticated', 'public')")
        return value

    @field_validator('upload_state')
    def upload_state_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['pending', 'duplicating', 'converting', 'analyzing', 'suspicious', 'file_too_large_to_analyze', 'ready']):
            raise ValueError("must be one of enum values ('pending', 'duplicating', 'converting', 'analyzing', 'suspicious', 'file_too_large_to_analyze', 'ready')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ListItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "abilities",
            "ancestors_link_reach",
            "ancestors_link_role",
            "computed_link_reach",
            "computed_link_role",
            "created_at",
            "creator",
            "depth",
            "is_favorite",
            "link_role",
            "link_reach",
            "is_restricted",
            "nb_accesses",
            "numchild",
            "numchild_folder",
            "path",
            "target",
            "updated_at",
            "user_role",
            "type",
            "upload_state",
            "url",
            "url_permalink",
            "url_preview",
            "mimetype",
            "main_workspace",
            "size",
            "description",
            "deleted_at",
            "hard_delete_at",
            "is_wopi_supported",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of creator
        if self.creator:
            _dict['creator'] = self.creator.to_dict()
        # override the default output from pydantic by calling `to_dict()` of target
        if self.target:
            _dict['target'] = self.target.to_dict()
        # set to None if link_reach (nullable) is None
        # and model_fields_set contains the field
        if self.link_reach is None and "link_reach" in self.model_fields_set:
            _dict['link_reach'] = None

        # set to None if target (nullable) is None
        # and model_fields_set contains the field
        if self.target is None and "target" in self.model_fields_set:
            _dict['target'] = None

        # set to None if upload_state (nullable) is None
        # and model_fields_set contains the field
        if self.upload_state is None and "upload_state" in self.model_fields_set:
            _dict['upload_state'] = None

        # set to None if filename (nullable) is None
        # and model_fields_set contains the field
        if self.filename is None and "filename" in self.model_fields_set:
            _dict['filename'] = None

        # set to None if mimetype (nullable) is None
        # and model_fields_set contains the field
        if self.mimetype is None and "mimetype" in self.model_fields_set:
            _dict['mimetype'] = None

        # set to None if size (nullable) is None
        # and model_fields_set contains the field
        if self.size is None and "size" in self.model_fields_set:
            _dict['size'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if deleted_at (nullable) is None
        # and model_fields_set contains the field
        if self.deleted_at is None and "deleted_at" in self.model_fields_set:
            _dict['deleted_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ListItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "abilities": obj.get("abilities"),
            "ancestors_link_reach": obj.get("ancestors_link_reach"),
            "ancestors_link_role": obj.get("ancestors_link_role"),
            "computed_link_reach": obj.get("computed_link_reach"),
            "computed_link_role": obj.get("computed_link_role"),
            "created_at": obj.get("created_at"),
            "creator": UserLight.from_dict(obj["creator"]) if obj.get("creator") is not None else None,
            "depth": obj.get("depth"),
            "is_favorite": obj.get("is_favorite"),
            "link_role": obj.get("link_role"),
            "link_reach": obj.get("link_reach"),
            "is_restricted": obj.get("is_restricted"),
            "nb_accesses": obj.get("nb_accesses"),
            "numchild": obj.get("numchild"),
            "numchild_folder": obj.get("numchild_folder"),
            "path": obj.get("path"),
            "target": RestrictionTarget.from_dict(obj["target"]) if obj.get("target") is not None else None,
            "title": obj.get("title"),
            "updated_at": obj.get("updated_at"),
            "user_role": obj.get("user_role"),
            "type": obj.get("type"),
            "upload_state": obj.get("upload_state"),
            "url": obj.get("url"),
            "url_permalink": obj.get("url_permalink"),
            "url_preview": obj.get("url_preview"),
            "filename": obj.get("filename"),
            "mimetype": obj.get("mimetype"),
            "main_workspace": obj.get("main_workspace"),
            "size": obj.get("size"),
            "description": obj.get("description"),
            "deleted_at": obj.get("deleted_at"),
            "hard_delete_at": obj.get("hard_delete_at"),
            "is_wopi_supported": obj.get("is_wopi_supported")
        })
        return _obj


