# coding: utf-8

"""
    drive API

    This is the drive API schema.

    The version of the OpenAPI document: 1.0.0 (v1.0)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UserRequest(BaseModel):
    """
    Serialize users.
    """ # noqa: E501
    language: Optional[StrictStr] = Field(default=None, description="The language in which the user wants to see the interface.  * `en-us` - English * `fr-fr` - French * `de-de` - German * `nl-nl` - Dutch")
    last_release_note_seen: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=85)]] = None
    column_preferences: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["language", "last_release_note_seen", "column_preferences"]

    @field_validator('language')
    def language_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['en-us', 'fr-fr', 'de-de', 'nl-nl', '']):
            raise ValueError("must be one of enum values ('en-us', 'fr-fr', 'de-de', 'nl-nl', '')")
        return value

    @field_validator('last_release_note_seen', mode="before")
    def last_release_note_seen_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^[0-9]+\.[0-9]+\.[0-9]+$", value):
            raise ValueError(r"must validate the regular expression /^[0-9]+\.[0-9]+\.[0-9]+$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UserRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if language (nullable) is None
        # and model_fields_set contains the field
        if self.language is None and "language" in self.model_fields_set:
            _dict['language'] = None

        # set to None if last_release_note_seen (nullable) is None
        # and model_fields_set contains the field
        if self.last_release_note_seen is None and "last_release_note_seen" in self.model_fields_set:
            _dict['last_release_note_seen'] = None

        # set to None if column_preferences (nullable) is None
        # and model_fields_set contains the field
        if self.column_preferences is None and "column_preferences" in self.model_fields_set:
            _dict['column_preferences'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "language": obj.get("language"),
            "last_release_note_seen": obj.get("last_release_note_seen"),
            "column_preferences": obj.get("column_preferences")
        })
        return _obj


