# coding: utf-8

"""
    drive API

    This is the drive API schema.

    The version of the OpenAPI document: 1.0.0 (v1.0)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.upload_state_enum import UploadStateEnum

class TestUploadStateEnum(unittest.TestCase):
    """UploadStateEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUploadStateEnum(self):
        """Test UploadStateEnum"""
        # inst = UploadStateEnum()

if __name__ == '__main__':
    unittest.main()
