# coding: utf-8

"""
    drive API

    This is the drive API schema.

    The version of the OpenAPI document: 1.0.0 (v1.0)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.extension_enum import ExtensionEnum

class TestExtensionEnum(unittest.TestCase):
    """ExtensionEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExtensionEnum(self):
        """Test ExtensionEnum"""
        # inst = ExtensionEnum()

if __name__ == '__main__':
    unittest.main()
