# coding: utf-8

"""
    drive API

    This is the drive API schema.

    The version of the OpenAPI document: 1.0.0 (v1.0)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.paginated_list_item_list import PaginatedListItemList

class TestPaginatedListItemList(unittest.TestCase):
    """PaginatedListItemList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedListItemList:
        """Test PaginatedListItemList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedListItemList`
        """
        model = PaginatedListItemList()
        if include_optional:
            return PaginatedListItemList(
                count = 123,
                next = 'http://api.example.org/accounts/?page=4',
                previous = 'http://api.example.org/accounts/?page=2',
                results = [
                    openapi_client.models.list_item.ListItem(
                        id = '', 
                        abilities = {
                            'key' : null
                            }, 
                        ancestors_link_reach = '', 
                        ancestors_link_role = '', 
                        computed_link_reach = '', 
                        computed_link_role = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        creator = null, 
                        depth = '', 
                        is_favorite = True, 
                        link_role = null, 
                        link_reach = 'restricted', 
                        is_restricted = '', 
                        nb_accesses = 56, 
                        numchild = '', 
                        numchild_folder = '', 
                        path = '', 
                        target = null, 
                        title = '', 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        user_role = '', 
                        type = null, 
                        upload_state = 'pending', 
                        url = '', 
                        url_permalink = '', 
                        url_preview = '', 
                        filename = '', 
                        mimetype = '', 
                        main_workspace = True, 
                        size = 56, 
                        description = '', 
                        deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        hard_delete_at = '', 
                        is_wopi_supported = '', )
                    ]
            )
        else:
            return PaginatedListItemList(
                count = 123,
                results = [
                    openapi_client.models.list_item.ListItem(
                        id = '', 
                        abilities = {
                            'key' : null
                            }, 
                        ancestors_link_reach = '', 
                        ancestors_link_role = '', 
                        computed_link_reach = '', 
                        computed_link_role = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        creator = null, 
                        depth = '', 
                        is_favorite = True, 
                        link_role = null, 
                        link_reach = 'restricted', 
                        is_restricted = '', 
                        nb_accesses = 56, 
                        numchild = '', 
                        numchild_folder = '', 
                        path = '', 
                        target = null, 
                        title = '', 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        user_role = '', 
                        type = null, 
                        upload_state = 'pending', 
                        url = '', 
                        url_permalink = '', 
                        url_preview = '', 
                        filename = '', 
                        mimetype = '', 
                        main_workspace = True, 
                        size = 56, 
                        description = '', 
                        deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        hard_delete_at = '', 
                        is_wopi_supported = '', )
                    ],
        )
        """

    def testPaginatedListItemList(self):
        """Test PaginatedListItemList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
