# coding: utf-8

"""
    drive API

    This is the drive API schema.

    The version of the OpenAPI document: 1.0.0 (v1.0)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.api_api import ApiApi


class TestApiApi(unittest.TestCase):
    """ApiApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ApiApi()

    def tearDown(self) -> None:
        pass

    def test_api_v1_0_config_retrieve(self) -> None:
        """Test case for api_v1_0_config_retrieve

        """
        pass

    def test_api_v1_0_entitlements_retrieve(self) -> None:
        """Test case for api_v1_0_entitlements_retrieve

        """
        pass

    def test_api_v1_0_items_accesses_create(self) -> None:
        """Test case for api_v1_0_items_accesses_create

        """
        pass

    def test_api_v1_0_items_accesses_destroy(self) -> None:
        """Test case for api_v1_0_items_accesses_destroy

        """
        pass

    def test_api_v1_0_items_accesses_list(self) -> None:
        """Test case for api_v1_0_items_accesses_list

        """
        pass

    def test_api_v1_0_items_accesses_partial_update(self) -> None:
        """Test case for api_v1_0_items_accesses_partial_update

        """
        pass

    def test_api_v1_0_items_accesses_retrieve(self) -> None:
        """Test case for api_v1_0_items_accesses_retrieve

        """
        pass

    def test_api_v1_0_items_accesses_update(self) -> None:
        """Test case for api_v1_0_items_accesses_update

        """
        pass

    def test_api_v1_0_items_batch_share_create(self) -> None:
        """Test case for api_v1_0_items_batch_share_create

        """
        pass

    def test_api_v1_0_items_breadcrumb_retrieve(self) -> None:
        """Test case for api_v1_0_items_breadcrumb_retrieve

        """
        pass

    def test_api_v1_0_items_children_create(self) -> None:
        """Test case for api_v1_0_items_children_create

        """
        pass

    def test_api_v1_0_items_children_retrieve(self) -> None:
        """Test case for api_v1_0_items_children_retrieve

        """
        pass

    def test_api_v1_0_items_convert_create(self) -> None:
        """Test case for api_v1_0_items_convert_create

        """
        pass

    def test_api_v1_0_items_create(self) -> None:
        """Test case for api_v1_0_items_create

        """
        pass

    def test_api_v1_0_items_destroy(self) -> None:
        """Test case for api_v1_0_items_destroy

        """
        pass

    def test_api_v1_0_items_download_retrieve(self) -> None:
        """Test case for api_v1_0_items_download_retrieve

        """
        pass

    def test_api_v1_0_items_duplicate_create(self) -> None:
        """Test case for api_v1_0_items_duplicate_create

        """
        pass

    def test_api_v1_0_items_export_retrieve(self) -> None:
        """Test case for api_v1_0_items_export_retrieve

        """
        pass

    def test_api_v1_0_items_favorite_create(self) -> None:
        """Test case for api_v1_0_items_favorite_create

        """
        pass

    def test_api_v1_0_items_favorite_destroy(self) -> None:
        """Test case for api_v1_0_items_favorite_destroy

        """
        pass

    def test_api_v1_0_items_favorites_retrieve(self) -> None:
        """Test case for api_v1_0_items_favorites_retrieve

        """
        pass

    def test_api_v1_0_items_hard_delete_destroy(self) -> None:
        """Test case for api_v1_0_items_hard_delete_destroy

        """
        pass

    def test_api_v1_0_items_invitations_create(self) -> None:
        """Test case for api_v1_0_items_invitations_create

        """
        pass

    def test_api_v1_0_items_invitations_destroy(self) -> None:
        """Test case for api_v1_0_items_invitations_destroy

        """
        pass

    def test_api_v1_0_items_invitations_list(self) -> None:
        """Test case for api_v1_0_items_invitations_list

        """
        pass

    def test_api_v1_0_items_invitations_partial_update(self) -> None:
        """Test case for api_v1_0_items_invitations_partial_update

        """
        pass

    def test_api_v1_0_items_invitations_retrieve(self) -> None:
        """Test case for api_v1_0_items_invitations_retrieve

        """
        pass

    def test_api_v1_0_items_invitations_update(self) -> None:
        """Test case for api_v1_0_items_invitations_update

        """
        pass

    def test_api_v1_0_items_link_configuration_update(self) -> None:
        """Test case for api_v1_0_items_link_configuration_update

        """
        pass

    def test_api_v1_0_items_list(self) -> None:
        """Test case for api_v1_0_items_list

        """
        pass

    def test_api_v1_0_items_media_auth_retrieve(self) -> None:
        """Test case for api_v1_0_items_media_auth_retrieve

        """
        pass

    def test_api_v1_0_items_move_create(self) -> None:
        """Test case for api_v1_0_items_move_create

        """
        pass

    def test_api_v1_0_items_partial_update(self) -> None:
        """Test case for api_v1_0_items_partial_update

        """
        pass

    def test_api_v1_0_items_recents_retrieve(self) -> None:
        """Test case for api_v1_0_items_recents_retrieve

        """
        pass

    def test_api_v1_0_items_restore_create(self) -> None:
        """Test case for api_v1_0_items_restore_create

        """
        pass

    def test_api_v1_0_items_restrict_create(self) -> None:
        """Test case for api_v1_0_items_restrict_create

        """
        pass

    def test_api_v1_0_items_restrict_destroy(self) -> None:
        """Test case for api_v1_0_items_restrict_destroy

        """
        pass

    def test_api_v1_0_items_retrieve(self) -> None:
        """Test case for api_v1_0_items_retrieve

        """
        pass

    def test_api_v1_0_items_search_retrieve(self) -> None:
        """Test case for api_v1_0_items_search_retrieve

        """
        pass

    def test_api_v1_0_items_trashbin_retrieve(self) -> None:
        """Test case for api_v1_0_items_trashbin_retrieve

        """
        pass

    def test_api_v1_0_items_tree_retrieve(self) -> None:
        """Test case for api_v1_0_items_tree_retrieve

        """
        pass

    def test_api_v1_0_items_update(self) -> None:
        """Test case for api_v1_0_items_update

        """
        pass

    def test_api_v1_0_items_upload_ended_create(self) -> None:
        """Test case for api_v1_0_items_upload_ended_create

        """
        pass

    def test_api_v1_0_items_wopi_retrieve(self) -> None:
        """Test case for api_v1_0_items_wopi_retrieve

        """
        pass

    def test_api_v1_0_sdk_relay_events_create(self) -> None:
        """Test case for api_v1_0_sdk_relay_events_create

        """
        pass

    def test_api_v1_0_sdk_relay_events_retrieve(self) -> None:
        """Test case for api_v1_0_sdk_relay_events_retrieve

        """
        pass

    def test_api_v1_0_user_reconciliations_retrieve(self) -> None:
        """Test case for api_v1_0_user_reconciliations_retrieve

        """
        pass

    def test_api_v1_0_users_contacts_retrieve(self) -> None:
        """Test case for api_v1_0_users_contacts_retrieve

        """
        pass

    def test_api_v1_0_users_list(self) -> None:
        """Test case for api_v1_0_users_list

        """
        pass

    def test_api_v1_0_users_me_retrieve(self) -> None:
        """Test case for api_v1_0_users_me_retrieve

        """
        pass

    def test_api_v1_0_users_partial_update(self) -> None:
        """Test case for api_v1_0_users_partial_update

        """
        pass

    def test_api_v1_0_users_update(self) -> None:
        """Test case for api_v1_0_users_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
