# coding: utf-8

"""
    drive API

    This is the drive API schema.

    The version of the OpenAPI document: 1.0.0 (v1.0)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.language_enum import LanguageEnum

class TestLanguageEnum(unittest.TestCase):
    """LanguageEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLanguageEnum(self):
        """Test LanguageEnum"""
        # inst = LanguageEnum()

if __name__ == '__main__':
    unittest.main()
