# coding: utf-8

"""
    drive API

    This is the drive API schema.

    The version of the OpenAPI document: 1.0.0 (v1.0)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.item_access import ItemAccess

class TestItemAccess(unittest.TestCase):
    """ItemAccess unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ItemAccess:
        """Test ItemAccess
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ItemAccess`
        """
        model = ItemAccess()
        if include_optional:
            return ItemAccess(
                id = '',
                user = openapi_client.models.user.User(
                    id = '', 
                    email = '', 
                    full_name = '', 
                    short_name = '', 
                    language = 'en-us', 
                    last_release_note_seen = '4.072888001528021798096225500850762068629.39333975650685139102691291732729478601482026', 
                    column_preferences = '', ),
                team = '',
                role = 'reader',
                abilities = '',
                max_ancestors_role = '',
                max_ancestors_role_item_id = '',
                max_role = '',
                item = openapi_client.models.item_light.ItemLight(
                    id = '', 
                    path = '', 
                    depth = '', ),
                is_explicit = ''
            )
        else:
            return ItemAccess(
                id = '',
                user = openapi_client.models.user.User(
                    id = '', 
                    email = '', 
                    full_name = '', 
                    short_name = '', 
                    language = 'en-us', 
                    last_release_note_seen = '4.072888001528021798096225500850762068629.39333975650685139102691291732729478601482026', 
                    column_preferences = '', ),
                abilities = '',
                max_ancestors_role = '',
                max_ancestors_role_item_id = '',
                max_role = '',
                item = openapi_client.models.item_light.ItemLight(
                    id = '', 
                    path = '', 
                    depth = '', ),
                is_explicit = '',
        )
        """

    def testItemAccess(self):
        """Test ItemAccess"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
