# coding: utf-8

"""
    drive API

    This is the drive API schema.

    The version of the OpenAPI document: 1.0.0 (v1.0)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.list_item import ListItem

class TestListItem(unittest.TestCase):
    """ListItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListItem:
        """Test ListItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListItem`
        """
        model = ListItem()
        if include_optional:
            return ListItem(
                id = '',
                abilities = {
                    'key' : null
                    },
                ancestors_link_reach = '',
                ancestors_link_role = '',
                computed_link_reach = '',
                computed_link_role = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                creator = openapi_client.models.user_light.UserLight(
                    id = '', 
                    full_name = '', 
                    short_name = '', ),
                depth = '',
                is_favorite = True,
                link_role = 'reader',
                link_reach = 'restricted',
                is_restricted = '',
                nb_accesses = 56,
                numchild = '',
                numchild_folder = '',
                path = '',
                target = openapi_client.models.restriction_target.RestrictionTarget(
                    id = '', 
                    title = '', 
                    is_restricted = True, 
                    deleted = True, 
                    can_access = True, ),
                title = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                user_role = '',
                type = 'folder',
                upload_state = 'pending',
                url = '',
                url_permalink = '',
                url_preview = '',
                filename = '',
                mimetype = '',
                main_workspace = True,
                size = 56,
                description = '',
                deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                hard_delete_at = '',
                is_wopi_supported = ''
            )
        else:
            return ListItem(
                id = '',
                abilities = {
                    'key' : null
                    },
                ancestors_link_reach = '',
                ancestors_link_role = '',
                computed_link_reach = '',
                computed_link_role = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                creator = openapi_client.models.user_light.UserLight(
                    id = '', 
                    full_name = '', 
                    short_name = '', ),
                depth = '',
                is_favorite = True,
                link_role = 'reader',
                link_reach = 'restricted',
                is_restricted = '',
                nb_accesses = 56,
                numchild = '',
                numchild_folder = '',
                path = '',
                target = openapi_client.models.restriction_target.RestrictionTarget(
                    id = '', 
                    title = '', 
                    is_restricted = True, 
                    deleted = True, 
                    can_access = True, ),
                title = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                user_role = '',
                type = 'folder',
                upload_state = 'pending',
                url = '',
                url_permalink = '',
                url_preview = '',
                mimetype = '',
                main_workspace = True,
                size = 56,
                description = '',
                deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                hard_delete_at = '',
                is_wopi_supported = '',
        )
        """

    def testListItem(self):
        """Test ListItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
