# coding: utf-8

"""
    drive API

    This is the drive API schema.

    The version of the OpenAPI document: 1.0.0 (v1.0)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_item import CreateItem

class TestCreateItem(unittest.TestCase):
    """CreateItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateItem:
        """Test CreateItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateItem`
        """
        model = CreateItem()
        if include_optional:
            return CreateItem(
                id = '',
                abilities = {
                    'key' : null
                    },
                ancestors_link_reach = '',
                ancestors_link_role = '',
                computed_link_reach = '',
                computed_link_role = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                creator = openapi_client.models.user_light.UserLight(
                    id = '', 
                    full_name = '', 
                    short_name = '', ),
                depth = '',
                is_favorite = True,
                link_role = 'reader',
                link_reach = 'restricted',
                nb_accesses = 56,
                numchild = '',
                numchild_folder = '',
                path = '',
                title = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                user_role = '',
                type = 'folder',
                upload_state = 'pending',
                url = '',
                url_permalink = '',
                filename = '',
                policy = '',
                main_workspace = True,
                size = 56,
                description = '',
                hard_delete_at = ''
            )
        else:
            return CreateItem(
                abilities = {
                    'key' : null
                    },
                ancestors_link_reach = '',
                ancestors_link_role = '',
                computed_link_reach = '',
                computed_link_role = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                creator = openapi_client.models.user_light.UserLight(
                    id = '', 
                    full_name = '', 
                    short_name = '', ),
                depth = '',
                is_favorite = True,
                link_role = 'reader',
                link_reach = 'restricted',
                nb_accesses = 56,
                numchild = '',
                numchild_folder = '',
                path = '',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                user_role = '',
                upload_state = 'pending',
                url = '',
                url_permalink = '',
                policy = '',
                main_workspace = True,
                size = 56,
                hard_delete_at = '',
        )
        """

    def testCreateItem(self):
        """Test CreateItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
