# coding: utf-8

"""
    drive API

    This is the drive API schema.

    The version of the OpenAPI document: 1.0.0 (v1.0)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.patched_user_request import PatchedUserRequest

class TestPatchedUserRequest(unittest.TestCase):
    """PatchedUserRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PatchedUserRequest:
        """Test PatchedUserRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PatchedUserRequest`
        """
        model = PatchedUserRequest()
        if include_optional:
            return PatchedUserRequest(
                language = 'en-us',
                last_release_note_seen = '4.072888001528021798096225500850762068629.393339756506851391026912917327294786014820260',
                column_preferences = ''
            )
        else:
            return PatchedUserRequest(
        )
        """

    def testPatchedUserRequest(self):
        """Test PatchedUserRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
