# coding: utf-8

"""
    drive API

    This is the drive API schema.

    The version of the OpenAPI document: 1.0.0 (v1.0)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.link_reach_enum import LinkReachEnum

class TestLinkReachEnum(unittest.TestCase):
    """LinkReachEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLinkReachEnum(self):
        """Test LinkReachEnum"""
        # inst = LinkReachEnum()

if __name__ == '__main__':
    unittest.main()
