# coding: utf-8

"""
    drive API

    This is the drive API schema.

    The version of the OpenAPI document: 1.0.0 (v1.0)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.batch_share_row_request import BatchShareRowRequest

class TestBatchShareRowRequest(unittest.TestCase):
    """BatchShareRowRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BatchShareRowRequest:
        """Test BatchShareRowRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BatchShareRowRequest`
        """
        model = BatchShareRowRequest()
        if include_optional:
            return BatchShareRowRequest(
                email = '0',
                role = 'reader'
            )
        else:
            return BatchShareRowRequest(
                email = '0',
                role = 'reader',
        )
        """

    def testBatchShareRowRequest(self):
        """Test BatchShareRowRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
