# coding: utf-8

"""
    drive API

    This is the drive API schema.

    The version of the OpenAPI document: 1.0.0 (v1.0)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.item_access_request import ItemAccessRequest

class TestItemAccessRequest(unittest.TestCase):
    """ItemAccessRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ItemAccessRequest:
        """Test ItemAccessRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ItemAccessRequest`
        """
        model = ItemAccessRequest()
        if include_optional:
            return ItemAccessRequest(
                user_id = '',
                team = '',
                role = 'reader'
            )
        else:
            return ItemAccessRequest(
        )
        """

    def testItemAccessRequest(self):
        """Test ItemAccessRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
