# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Access(str, Enum):
    """
    Access
    """

    """
    allowed enum values
    """
    OWNERS = 'owners'
    EDITORS = 'editors'
    VIEWERS = 'viewers'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Access from a JSON string"""
        return cls(json.loads(json_str))


