# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class CreateDocUnifiedRequest(BaseModel):
    """
    CreateDocUnifiedRequest
    """ # noqa: E501
    workspace_id: Optional[StrictInt] = Field(default=None, description="The workspace to save the document in. If omitted, creates an unsaved document.", alias="workspaceId")
    document_name: Optional[StrictStr] = Field(default=None, description="Name for the new document (required when copying)", alias="documentName")
    source_document_id: Optional[StrictStr] = Field(default=None, description="ID of document to copy from. Requires workspaceId and documentName.", alias="sourceDocumentId")
    as_template: Optional[StrictBool] = Field(default=None, description="When copying, if true, copy structure only without data", alias="asTemplate")
    timezone: Optional[StrictStr] = Field(default=None, description="Timezone for the document")
    __properties: ClassVar[List[str]] = ["workspaceId", "documentName", "sourceDocumentId", "asTemplate", "timezone"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateDocUnifiedRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateDocUnifiedRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "workspaceId": obj.get("workspaceId"),
            "documentName": obj.get("documentName"),
            "sourceDocumentId": obj.get("sourceDocumentId"),
            "asTemplate": obj.get("asTemplate"),
            "timezone": obj.get("timezone")
        })
        return _obj


