# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class PostSearch(BaseModel):
    """
    PostSearch
    """ # noqa: E501
    schemas: Optional[List[StrictStr]] = None
    filter: Optional[StrictStr] = Field(default=None, description="Filter expression for resources.")
    sort_by: Optional[StrictStr] = Field(default=None, description="Field to sort by.", alias="sortBy")
    sort_order: Optional[StrictStr] = Field(default=None, description="Order of sorting (ascending or descending).", alias="sortOrder")
    attributes: Optional[List[StrictStr]] = Field(default=None, description="A multi-valued list of strings indicating the names of resource attributes to return in the response.")
    excluded_attributes: Optional[List[StrictStr]] = Field(default=None, description="A multi-valued list of strings indicating the names of resource attributes to be removed from the default set of attributes to return.", alias="excludedAttributes")
    start_index: Optional[StrictInt] = Field(default=None, description="The starting index for pagination.", alias="startIndex")
    count: Optional[StrictInt] = Field(default=None, description="The number of resources to retrieve.")
    __properties: ClassVar[List[str]] = ["schemas", "filter", "sortBy", "sortOrder", "attributes", "excludedAttributes", "startIndex", "count"]

    @field_validator('schemas')
    def schemas_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['urn:ietf:params:scim:api:messages:2.0:SearchRequest']):
                raise ValueError("each list item must be one of ('urn:ietf:params:scim:api:messages:2.0:SearchRequest')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PostSearch from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PostSearch from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "schemas": obj.get("schemas"),
            "filter": obj.get("filter"),
            "sortBy": obj.get("sortBy"),
            "sortOrder": obj.get("sortOrder"),
            "attributes": obj.get("attributes"),
            "excludedAttributes": obj.get("excludedAttributes"),
            "startIndex": obj.get("startIndex"),
            "count": obj.get("count")
        })
        return _obj


