# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class UpdateColumnsColumnsInnerFields(BaseModel):
    """
    UpdateColumnsColumnsInnerFields
    """ # noqa: E501
    type: Optional[StrictStr] = Field(default=None, description="Column type, by default Any. Ref, RefList and DateTime types requires a postfix, e.g. <code>DateTime:America/New_York</code>, <code>Ref:Users</code>")
    label: Optional[StrictStr] = Field(default=None, description="Column label.")
    formula: Optional[StrictStr] = Field(default=None, description="A python formula, e.g.: <code>$A + Table1.lookupOne(B=$B)</code>")
    is_formula: Optional[StrictBool] = Field(default=None, description="Use \"true\" to indicate that the column is a formula column. Use \"false\" for trigger formula column.", alias="isFormula")
    widget_options: Optional[StrictStr] = Field(default=None, description="A JSON object with widget options, e.g.: <code>{\"choices\": [\"cat\", \"dog\"], \"alignment\": \"right\"}</code>", alias="widgetOptions")
    untie_col_id_from_label: Optional[StrictBool] = Field(default=None, description="Use \"true\" to indicate that the column label should not be used as the column identifier. Use \"false\" to use the label as the identifier.", alias="untieColIdFromLabel")
    recalc_when: Optional[StrictInt] = Field(default=None, description="A number indicating when the column should be recalculated. <ol start='0'><li>On new records or when any field in recalcDeps changes, it's a 'data-cleaning'.</li><li>Never.</li><li>Calculate on new records and on manual updates to any data field.</li></ol>", alias="recalcWhen")
    visible_col: Optional[StrictInt] = Field(default=None, description="For Ref and RefList columns, the colRef of a column to display", alias="visibleCol")
    recalc_deps: Optional[StrictStr] = Field(default=None, description="An encoded array of column identifiers (colRefs) that this column depends on. If any of these columns change, the column will be recalculated. E.g.: <code>[2, 3]</code>", alias="recalcDeps")
    col_id: Optional[StrictStr] = Field(default=None, description="Set it to the new column ID when you want to change it.", alias="colId")
    __properties: ClassVar[List[str]] = ["type", "label", "formula", "isFormula", "widgetOptions", "untieColIdFromLabel", "recalcWhen", "visibleCol", "recalcDeps", "colId"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Any', 'Text', 'Numeric', 'Int', 'Bool', 'Date', 'DateTime:<timezone>', 'Choice', 'ChoiceList', 'Ref:<tableId>', 'RefList:<tableId>', 'Attachments']):
            raise ValueError("must be one of enum values ('Any', 'Text', 'Numeric', 'Int', 'Bool', 'Date', 'DateTime:<timezone>', 'Choice', 'ChoiceList', 'Ref:<tableId>', 'RefList:<tableId>', 'Attachments')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateColumnsColumnsInnerFields from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateColumnsColumnsInnerFields from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "label": obj.get("label"),
            "formula": obj.get("formula"),
            "isFormula": obj.get("isFormula"),
            "widgetOptions": obj.get("widgetOptions"),
            "untieColIdFromLabel": obj.get("untieColIdFromLabel"),
            "recalcWhen": obj.get("recalcWhen"),
            "visibleCol": obj.get("visibleCol"),
            "recalcDeps": obj.get("recalcDeps"),
            "colId": obj.get("colId")
        })
        return _obj


