# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from grist_client.models.user_in_response import UserInResponse
from typing import Optional, Set
from typing_extensions import Self

class UsersListResponse(BaseModel):
    """
    UsersListResponse
    """ # noqa: E501
    schemas: Optional[List[StrictStr]] = None
    total_results: Optional[StrictInt] = Field(default=None, description="Total number of users.", alias="totalResults")
    items_per_page: Optional[StrictInt] = Field(default=None, description="Number of users returned per page.", alias="itemsPerPage")
    start_index: Optional[StrictInt] = Field(default=None, description="Starting index.", alias="startIndex")
    resources: Optional[List[UserInResponse]] = Field(default=None, alias="Resources")
    __properties: ClassVar[List[str]] = ["schemas", "totalResults", "itemsPerPage", "startIndex", "Resources"]

    @field_validator('schemas')
    def schemas_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['urn:ietf:params:scim:api:messages:2.0:ListResponse']):
                raise ValueError("each list item must be one of ('urn:ietf:params:scim:api:messages:2.0:ListResponse')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UsersListResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in resources (list)
        _items = []
        if self.resources:
            for _item_resources in self.resources:
                if _item_resources:
                    _items.append(_item_resources.to_dict())
            _dict['Resources'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UsersListResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "schemas": obj.get("schemas"),
            "totalResults": obj.get("totalResults"),
            "itemsPerPage": obj.get("itemsPerPage"),
            "startIndex": obj.get("startIndex"),
            "Resources": [UserInResponse.from_dict(_item) for _item in obj["Resources"]] if obj.get("Resources") is not None else None
        })
        return _obj


