# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class WebhookFields(BaseModel):
    """
    WebhookFields
    """ # noqa: E501
    name: Optional[StrictStr]
    memo: Optional[StrictStr]
    url: StrictStr
    enabled: StrictBool
    event_types: List[StrictStr] = Field(alias="eventTypes")
    is_ready_column: Optional[StrictStr] = Field(alias="isReadyColumn")
    table_id: StrictStr = Field(alias="tableId")
    unsubscribe_key: StrictStr = Field(alias="unsubscribeKey")
    __properties: ClassVar[List[str]] = ["name", "memo", "url", "enabled", "eventTypes", "isReadyColumn", "tableId", "unsubscribeKey"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WebhookFields from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if memo (nullable) is None
        # and model_fields_set contains the field
        if self.memo is None and "memo" in self.model_fields_set:
            _dict['memo'] = None

        # set to None if is_ready_column (nullable) is None
        # and model_fields_set contains the field
        if self.is_ready_column is None and "is_ready_column" in self.model_fields_set:
            _dict['isReadyColumn'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WebhookFields from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "memo": obj.get("memo"),
            "url": obj.get("url"),
            "enabled": obj.get("enabled"),
            "eventTypes": obj.get("eventTypes"),
            "isReadyColumn": obj.get("isReadyColumn"),
            "tableId": obj.get("tableId"),
            "unsubscribeKey": obj.get("unsubscribeKey")
        })
        return _obj


