# coding: utf-8

"""
    Grist API

    An API for manipulating Grist sites, workspaces, and documents.  # Authentication  The Grist API accepts two credential types in the `Authorization: Bearer` header: [API keys](../rest-api/) and [OAuth access tokens](../oauth-apps/).  <SecurityDefinitions /> 

    The version of the OpenAPI document: 1.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from grist_client.models.webhook_batch_status import WebhookBatchStatus
from typing import Optional, Set
from typing_extensions import Self

class WebhookUsage(BaseModel):
    """
    WebhookUsage
    """ # noqa: E501
    num_waiting: StrictInt = Field(alias="numWaiting")
    status: StrictStr
    updated_time: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="updatedTime")
    last_success_time: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="lastSuccessTime")
    last_failure_time: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="lastFailureTime")
    last_error_message: Optional[StrictStr] = Field(default=None, alias="lastErrorMessage")
    last_http_status: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="lastHttpStatus")
    last_event_batch: Optional[WebhookBatchStatus] = Field(default=None, alias="lastEventBatch")
    __properties: ClassVar[List[str]] = ["numWaiting", "status", "updatedTime", "lastSuccessTime", "lastFailureTime", "lastErrorMessage", "lastHttpStatus", "lastEventBatch"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WebhookUsage from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of last_event_batch
        if self.last_event_batch:
            _dict['lastEventBatch'] = self.last_event_batch.to_dict()
        # set to None if updated_time (nullable) is None
        # and model_fields_set contains the field
        if self.updated_time is None and "updated_time" in self.model_fields_set:
            _dict['updatedTime'] = None

        # set to None if last_success_time (nullable) is None
        # and model_fields_set contains the field
        if self.last_success_time is None and "last_success_time" in self.model_fields_set:
            _dict['lastSuccessTime'] = None

        # set to None if last_failure_time (nullable) is None
        # and model_fields_set contains the field
        if self.last_failure_time is None and "last_failure_time" in self.model_fields_set:
            _dict['lastFailureTime'] = None

        # set to None if last_error_message (nullable) is None
        # and model_fields_set contains the field
        if self.last_error_message is None and "last_error_message" in self.model_fields_set:
            _dict['lastErrorMessage'] = None

        # set to None if last_http_status (nullable) is None
        # and model_fields_set contains the field
        if self.last_http_status is None and "last_http_status" in self.model_fields_set:
            _dict['lastHttpStatus'] = None

        # set to None if last_event_batch (nullable) is None
        # and model_fields_set contains the field
        if self.last_event_batch is None and "last_event_batch" in self.model_fields_set:
            _dict['lastEventBatch'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WebhookUsage from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "numWaiting": obj.get("numWaiting"),
            "status": obj.get("status"),
            "updatedTime": obj.get("updatedTime"),
            "lastSuccessTime": obj.get("lastSuccessTime"),
            "lastFailureTime": obj.get("lastFailureTime"),
            "lastErrorMessage": obj.get("lastErrorMessage"),
            "lastHttpStatus": obj.get("lastHttpStatus"),
            "lastEventBatch": WebhookBatchStatus.from_dict(obj["lastEventBatch"]) if obj.get("lastEventBatch") is not None else None
        })
        return _obj


